CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS dailyMenu (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    day DATETIME NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    calories INT
);

CREATE TABLE IF NOT EXISTS dailyMenuContainsMeals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mealsId INT NOT NULL,
    dailyMenuId INT NOT NULL,
    FOREIGN KEY(mealsId) REFERENCES meals(id),
    FOREIGN KEY(dailyMenuId) REFERENCES dailyMenu(id),
    UNIQUE (mealsId, dailyMenuId)
);
